name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
          
    env:
      VCPKG_ROOT: './vcpkg'
      BUILD_TYPE: 'Release'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with: 
          repository: 'microsoft/vcpkg'
          path: 'vcpkg'

      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1

      - name: 'Setup vcpkg'
        run: ./vcpkg/bootstrap-vcpkg.bat

      # This step assumes `vcpkg` has been bootstrapped (run `./vcpkg/bootstrap-vcpkg`)
      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        # Replace <OWNER> with your organization name
        run: >
          `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/tartanllama/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "tartanllama"
          -password "${{ secrets.GITHUB_TOKEN }}"
               
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build --preset=windows-default

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
